# Generated by Django 5.0.2 on 2024-12-09 08:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('excel_connector', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='excelsheetparsingrule',
            name='description_column',
            field=models.CharField(blank=True, help_text='Название колонки для описания', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='excelsheetparsingrule',
            name='image_column',
            field=models.CharField(blank=True, help_text='Название колонки для изображения', max_length=100, null=True),
        ),
    ]
