# Generated by Django 5.0.2 on 2024-12-09 09:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('excel_connector', '0002_excelsheetparsingrule_description_column_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='excelparsingsettings',
            name='exclude_sheets',
        ),
        migrations.RemoveField(
            model_name='excelparsingsettings',
            name='required_columns',
        ),
    ]
