# Generated by Django 5.0.2 on 2024-12-20 08:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='integrateproduct',
            name='product_code',
            field=models.CharField(default=1, max_length=100, verbose_name='Product Code'),
            preserve_default=False,
        ),
    ]
