# Generated by Django 5.0.2 on 2024-12-10 05:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gpt_connector', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='gptconnectorsettings',
            name='token_limit',
            field=models.IntegerField(default=100000, help_text='Общий лимит токенов'),
        ),
        migrations.AddField(
            model_name='gptconnectorsettings',
            name='tokens_used',
            field=models.IntegerField(default=0, help_text='Количество использованных токенов'),
        ),
    ]
