# Generated by Django 5.0.2 on 2024-12-12 10:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Email',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('to_email', models.EmailField(help_text="Recipient's email address.", max_length=254, verbose_name='Recipient')),
                ('subject', models.CharField(help_text='Subject of the email.', max_length=255, verbose_name='Subject')),
                ('body', models.TextField(help_text='HTML content of the email.', verbose_name='Body')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('sent', 'Sent'), ('failed', 'Failed')], default='pending', help_text='Status of the email.', max_length=10, verbose_name='Status')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('sent_at', models.DateTimeField(blank=True, help_text='Timestamp of when the email was sent.', null=True, verbose_name='Sent At')),
            ],
            options={
                'verbose_name': 'Email',
                'verbose_name_plural': 'Emails',
            },
        ),
        migrations.CreateModel(
            name='EmailTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Unique name for the email template.', max_length=100, unique=True, verbose_name='Template Name')),
                ('subject', models.CharField(help_text='Subject of the email.', max_length=255, verbose_name='Subject')),
                ('body', models.TextField(help_text='HTML content of the email.', verbose_name='Body')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
            ],
            options={
                'verbose_name': 'Email Template',
                'verbose_name_plural': 'Email Templates',
            },
        ),
        migrations.CreateModel(
            name='ScheduledEmail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('to_email', models.EmailField(help_text="Recipient's email address.", max_length=254, verbose_name='Recipient')),
                ('scheduled_time', models.DateTimeField(help_text='Time when the email should be sent.', verbose_name='Scheduled Time')),
                ('is_sent', models.BooleanField(default=False, help_text='Whether the email has been sent.', verbose_name='Is Sent')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('email_template', models.ForeignKey(help_text='Template to use for the scheduled email.', on_delete=django.db.models.deletion.CASCADE, to='mailer.emailtemplate', verbose_name='Email Template')),
            ],
            options={
                'verbose_name': 'Scheduled Email',
                'verbose_name_plural': 'Scheduled Emails',
            },
        ),
    ]
