# Generated by Django 5.0.2 on 2024-12-12 12:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mailer', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmailUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(help_text="User's first name.", max_length=100, verbose_name='First Name')),
                ('last_name', models.CharField(help_text="User's last name.", max_length=100, verbose_name='Last Name')),
                ('email', models.EmailField(help_text="User's email address.", max_length=254, unique=True, verbose_name='Email')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
            ],
            options={
                'verbose_name': 'User Profile',
                'verbose_name_plural': 'User Profiles',
            },
        ),
        migrations.RemoveField(
            model_name='scheduledemail',
            name='to_email',
        ),
        migrations.AddField(
            model_name='scheduledemail',
            name='user_profile',
            field=models.ForeignKey(default=1, help_text='User profile associated with the email.', on_delete=django.db.models.deletion.CASCADE, to='mailer.emailuser', verbose_name='User Profile'),
            preserve_default=False,
        ),
    ]
