# Generated by Django 5.0.2 on 2024-12-09 06:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('supplier', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PriceReplacementRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('find_str', models.CharField(max_length=255, verbose_name='Искомая строка')),
                ('replace_str', models.CharField(blank=True, max_length=255, null=True, verbose_name='Строка замены')),
            ],
            options={
                'verbose_name': 'Правило замены цены',
                'verbose_name_plural': 'Правила замены цен',
            },
        ),
        migrations.CreateModel(
            name='XMLParsingRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('base_url', models.URLField(help_text='Базовый URL XML', verbose_name='Базовый URL XML')),
                ('element_path', models.CharField(default='shop/offers/offer', help_text='XPath путь к элементу предложения', max_length=255)),
                ('title_field', models.CharField(default='name', help_text='Название тега для заголовка товара', max_length=255)),
                ('description_field', models.CharField(default='description', max_length=255)),
                ('article_field', models.CharField(default='article', help_text='Название тега для артикула', max_length=255)),
                ('price_field', models.CharField(default='price', help_text='Название тега для цены', max_length=255)),
                ('image_field', models.CharField(blank=True, default='picture', help_text='Название тега для изображения', max_length=255, null=True)),
                ('category_field', models.CharField(blank=True, default='categoryId', help_text='Название тега для категории', max_length=255, null=True)),
                ('link_field', models.CharField(blank=True, default='url', help_text='Название тега для ссылки', max_length=255, null=True)),
                ('parse_price', models.BooleanField(default=False, help_text='Указывает, нужно ли парсить цену напрямую с сайта', verbose_name='Парсить цену с сайта')),
                ('price_selector', models.CharField(blank=True, help_text='CSS-селектор или XPath для цены', max_length=255, null=True)),
                ('parse_image', models.BooleanField(default=False, help_text='Указывает, нужно ли парсить изображение напрямую с сайта', verbose_name='Парсить изображение с сайта')),
                ('price_replace', models.ManyToManyField(blank=True, related_name='products', to='yml_connector.pricereplacementrule')),
                ('supplier', models.ForeignKey(limit_choices_to={'formats': 'YML'}, on_delete=django.db.models.deletion.CASCADE, related_name='xml_parsing_rules', to='supplier.supplier')),
            ],
        ),
    ]
