# Generated by Django 5.0.2 on 2024-12-09 06:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='OneCConfiguration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Название конфигурации')),
                ('description', models.TextField(blank=True, verbose_name='Описание')),
                ('active', models.BooleanField(default=True, verbose_name='Активна')),
            ],
            options={
                'verbose_name': 'Конфигурация 1С',
                'verbose_name_plural': 'Конфигурации 1С',
            },
        ),
        migrations.CreateModel(
            name='OneCConnection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.URLField(verbose_name='URL сервера 1С')),
                ('username', models.CharField(max_length=50, verbose_name='Имя пользователя')),
                ('password', models.CharField(max_length=100, verbose_name='Пароль')),
                ('database', models.CharField(max_length=100, verbose_name='Название базы данных')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
                ('config', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='connections', to='onec_connector.onecconfiguration', verbose_name='Конфигурация')),
            ],
            options={
                'verbose_name': 'Подключение к 1С',
                'verbose_name_plural': 'Подключения к 1С',
            },
        ),
    ]
